/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ContextsRouteImport } from './routes/contexts'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as ImageGenerateRouteImport } from './routes/image-generate'
import { Route as ImageGenerationsRouteImport } from './routes/image-generations'
import { Route as ImageSettingsRouteImport } from './routes/image-settings'
import { Route as InvocationsRouteImport } from './routes/invocations'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StickersRouteImport } from './routes/stickers'
import { Route as ContextsConversationIdRouteImport } from './routes/contexts_.$conversationId'
import { Route as ImageGenerationsGenerationIdRouteImport } from './routes/image-generations_.$generationId'
import { Route as InvocationsInvocationIdRouteImport } from './routes/invocations_.$invocationId'
import { Route as MessagesMessageIdRouteImport } from './routes/messages_.$messageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsRoute = ContextsRouteImport.update({
  id: '/contexts',
  path: '/contexts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGenerateRoute = ImageGenerateRouteImport.update({
  id: '/image-generate',
  path: '/image-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGenerationsRoute = ImageGenerationsRouteImport.update({
  id: '/image-generations',
  path: '/image-generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSettingsRoute = ImageSettingsRouteImport.update({
  id: '/image-settings',
  path: '/image-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvocationsRoute = InvocationsRouteImport.update({
  id: '/invocations',
  path: '/invocations',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StickersRoute = StickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsConversationIdRoute = ContextsConversationIdRouteImport.update({
  id: '/contexts_/$conversationId',
  path: '/contexts/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGenerationsGenerationIdRoute =
  ImageGenerationsGenerationIdRouteImport.update({
    id: '/image-generations_/$generationId',
    path: '/image-generations/$generationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvocationsInvocationIdRoute = InvocationsInvocationIdRouteImport.update({
  id: '/invocations_/$invocationId',
  path: '/invocations/$invocationId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesMessageIdRoute = MessagesMessageIdRouteImport.update({
  id: '/messages_/$messageId',
  path: '/messages/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/alarms': typeof AlarmsRoute
  '/api-keys': typeof ApiKeysRoute
  '/chats': typeof ChatsRoute
  '/contexts': typeof ContextsRoute
  '/developer': typeof DeveloperRoute
  '/image-generate': typeof ImageGenerateRoute
  '/image-generations': typeof ImageGenerationsRoute
  '/image-settings': typeof ImageSettingsRoute
  '/invocations': typeof InvocationsRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/models': typeof ModelsRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/stickers': typeof StickersRoute
  '/contexts/$conversationId': typeof ContextsConversationIdRoute
  '/image-generations/$generationId': typeof ImageGenerationsGenerationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/alarms': typeof AlarmsRoute
  '/api-keys': typeof ApiKeysRoute
  '/chats': typeof ChatsRoute
  '/contexts': typeof ContextsRoute
  '/developer': typeof DeveloperRoute
  '/image-generate': typeof ImageGenerateRoute
  '/image-generations': typeof ImageGenerationsRoute
  '/image-settings': typeof ImageSettingsRoute
  '/invocations': typeof InvocationsRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/models': typeof ModelsRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/stickers': typeof StickersRoute
  '/contexts/$conversationId': typeof ContextsConversationIdRoute
  '/image-generations/$generationId': typeof ImageGenerationsGenerationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/alarms': typeof AlarmsRoute
  '/api-keys': typeof ApiKeysRoute
  '/chats': typeof ChatsRoute
  '/contexts': typeof ContextsRoute
  '/developer': typeof DeveloperRoute
  '/image-generate': typeof ImageGenerateRoute
  '/image-generations': typeof ImageGenerationsRoute
  '/image-settings': typeof ImageSettingsRoute
  '/invocations': typeof InvocationsRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/models': typeof ModelsRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/stickers': typeof StickersRoute
  '/contexts_/$conversationId': typeof ContextsConversationIdRoute
  '/image-generations_/$generationId': typeof ImageGenerationsGenerationIdRoute
  '/invocations_/$invocationId': typeof InvocationsInvocationIdRoute
  '/messages_/$messageId': typeof MessagesMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/alarms'
    | '/api-keys'
    | '/chats'
    | '/contexts'
    | '/developer'
    | '/image-generate'
    | '/image-generations'
    | '/image-settings'
    | '/invocations'
    | '/memories'
    | '/messages'
    | '/models'
    | '/prompts'
    | '/settings'
    | '/stickers'
    | '/contexts/$conversationId'
    | '/image-generations/$generationId'
    | '/invocations/$invocationId'
    | '/messages/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/alarms'
    | '/api-keys'
    | '/chats'
    | '/contexts'
    | '/developer'
    | '/image-generate'
    | '/image-generations'
    | '/image-settings'
    | '/invocations'
    | '/memories'
    | '/messages'
    | '/models'
    | '/prompts'
    | '/settings'
    | '/stickers'
    | '/contexts/$conversationId'
    | '/image-generations/$generationId'
    | '/invocations/$invocationId'
    | '/messages/$messageId'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/alarms'
    | '/api-keys'
    | '/chats'
    | '/contexts'
    | '/developer'
    | '/image-generate'
    | '/image-generations'
    | '/image-settings'
    | '/invocations'
    | '/memories'
    | '/messages'
    | '/models'
    | '/prompts'
    | '/settings'
    | '/stickers'
    | '/contexts_/$conversationId'
    | '/image-generations_/$generationId'
    | '/invocations_/$invocationId'
    | '/messages_/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  AlarmsRoute: typeof AlarmsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ChatsRoute: typeof ChatsRoute
  ContextsRoute: typeof ContextsRoute
  DeveloperRoute: typeof DeveloperRoute
  ImageGenerateRoute: typeof ImageGenerateRoute
  ImageGenerationsRoute: typeof ImageGenerationsRoute
  ImageSettingsRoute: typeof ImageSettingsRoute
  InvocationsRoute: typeof InvocationsRoute
  MemoriesRoute: typeof MemoriesRoute
  MessagesRoute: typeof MessagesRoute
  ModelsRoute: typeof ModelsRoute
  PromptsRoute: typeof PromptsRoute
  SettingsRoute: typeof SettingsRoute
  StickersRoute: typeof StickersRoute
  ContextsConversationIdRoute: typeof ContextsConversationIdRoute
  ImageGenerationsGenerationIdRoute: typeof ImageGenerationsGenerationIdRoute
  InvocationsInvocationIdRoute: typeof InvocationsInvocationIdRoute
  MessagesMessageIdRoute: typeof MessagesMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts': {
      id: '/contexts'
      path: '/contexts'
      fullPath: '/contexts'
      preLoaderRoute: typeof ContextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-generate': {
      id: '/image-generate'
      path: '/image-generate'
      fullPath: '/image-generate'
      preLoaderRoute: typeof ImageGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-generations': {
      id: '/image-generations'
      path: '/image-generations'
      fullPath: '/image-generations'
      preLoaderRoute: typeof ImageGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-settings': {
      id: '/image-settings'
      path: '/image-settings'
      fullPath: '/image-settings'
      preLoaderRoute: typeof ImageSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations': {
      id: '/invocations'
      path: '/invocations'
      fullPath: '/invocations'
      preLoaderRoute: typeof InvocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stickers': {
      id: '/stickers'
      path: '/stickers'
      fullPath: '/stickers'
      preLoaderRoute: typeof StickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts_/$conversationId': {
      id: '/contexts_/$conversationId'
      path: '/contexts/$conversationId'
      fullPath: '/contexts/$conversationId'
      preLoaderRoute: typeof ContextsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-generations_/$generationId': {
      id: '/image-generations_/$generationId'
      path: '/image-generations/$generationId'
      fullPath: '/image-generations/$generationId'
      preLoaderRoute: typeof ImageGenerationsGenerationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations_/$invocationId': {
      id: '/invocations_/$invocationId'
      path: '/invocations/$invocationId'
      fullPath: '/invocations/$invocationId'
      preLoaderRoute: typeof InvocationsInvocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages_/$messageId': {
      id: '/messages_/$messageId'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  AlarmsRoute: AlarmsRoute,
  ApiKeysRoute: ApiKeysRoute,
  ChatsRoute: ChatsRoute,
  ContextsRoute: ContextsRoute,
  DeveloperRoute: DeveloperRoute,
  ImageGenerateRoute: ImageGenerateRoute,
  ImageGenerationsRoute: ImageGenerationsRoute,
  ImageSettingsRoute: ImageSettingsRoute,
  InvocationsRoute: InvocationsRoute,
  MemoriesRoute: MemoriesRoute,
  MessagesRoute: MessagesRoute,
  ModelsRoute: ModelsRoute,
  PromptsRoute: PromptsRoute,
  SettingsRoute: SettingsRoute,
  StickersRoute: StickersRoute,
  ContextsConversationIdRoute: ContextsConversationIdRoute,
  ImageGenerationsGenerationIdRoute: ImageGenerationsGenerationIdRoute,
  InvocationsInvocationIdRoute: InvocationsInvocationIdRoute,
  MessagesMessageIdRoute: MessagesMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
